// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/notifyv1/notification.proto

package notifyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_CHANNEL_APPRISE     Channel = 1
	Channel_CHANNEL_DISCORD     Channel = 2
	Channel_CHANNEL_SLACK       Channel = 3
	Channel_CHANNEL_WEBHOOK     Channel = 4
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_APPRISE",
		2: "CHANNEL_DISCORD",
		3: "CHANNEL_SLACK",
		4: "CHANNEL_WEBHOOK",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_APPRISE":     1,
		"CHANNEL_DISCORD":     2,
		"CHANNEL_SLACK":       3,
		"CHANNEL_WEBHOOK":     4,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notifyv1_notification_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_proto_notifyv1_notification_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_proto_notifyv1_notification_proto_rawDescGZIP(), []int{0}
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	SourceModule  string                 `protobuf:"bytes,4,opt,name=source_module,json=sourceModule,proto3" json:"source_module,omitempty"`
	Channels      []Channel              `protobuf:"varint,5,rep,packed,name=channels,proto3,enum=muxcore.notification.apprise.v1.Channel" json:"channels,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_proto_notifyv1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifyv1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_notifyv1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotifyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotifyRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *NotifyRequest) GetSourceModule() string {
	if x != nil {
		return x.SourceModule
	}
	return ""
}

func (x *NotifyRequest) GetChannels() []Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *NotifyRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ChannelResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_proto_notifyv1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifyv1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_notifyv1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyResponse) GetResults() []*ChannelResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ChannelResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       Channel                `protobuf:"varint,1,opt,name=channel,proto3,enum=muxcore.notification.apprise.v1.Channel" json:"channel,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelResult) Reset() {
	*x = ChannelResult{}
	mi := &file_proto_notifyv1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelResult) ProtoMessage() {}

func (x *ChannelResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifyv1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelResult.ProtoReflect.Descriptor instead.
func (*ChannelResult) Descriptor() ([]byte, []int) {
	return file_proto_notifyv1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelResult) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *ChannelResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChannelResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       Channel                `protobuf:"varint,1,opt,name=channel,proto3,enum=muxcore.notification.apprise.v1.Channel" json:"channel,omitempty"`
	Settings      map[string]string      `protobuf:"bytes,2,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_notifyv1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifyv1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_notifyv1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureRequest) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *ConfigureRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configured    bool                   `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_notifyv1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifyv1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_notifyv1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_notifyv1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifyv1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_notifyv1_notification_proto_rawDescGZIP(), []int{5}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*ChannelStatus       `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_notifyv1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifyv1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_notifyv1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetChannels() []*ChannelStatus {
	if x != nil {
		return x.Channels
	}
	return nil
}

type ChannelStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       Channel                `protobuf:"varint,1,opt,name=channel,proto3,enum=muxcore.notification.apprise.v1.Channel" json:"channel,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelStatus) Reset() {
	*x = ChannelStatus{}
	mi := &file_proto_notifyv1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelStatus) ProtoMessage() {}

func (x *ChannelStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifyv1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelStatus.ProtoReflect.Descriptor instead.
func (*ChannelStatus) Descriptor() ([]byte, []int) {
	return file_proto_notifyv1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *ChannelStatus) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *ChannelStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ChannelStatus) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_notifyv1_notification_proto protoreflect.FileDescriptor

const file_proto_notifyv1_notification_proto_rawDesc = "" +
	"\n" +
	"!proto/notifyv1/notification.proto\x12\x1fmuxcore.notification.apprise.v1\"\xd5\x02\n" +
	"\rNotifyRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12#\n" +
	"\rsource_module\x18\x04 \x01(\tR\fsourceModule\x12D\n" +
	"\bchannels\x18\x05 \x03(\x0e2(.muxcore.notification.apprise.v1.ChannelR\bchannels\x12R\n" +
	"\x06fields\x18\x06 \x03(\v2:.muxcore.notification.apprise.v1.NotifyRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x0eNotifyResponse\x12H\n" +
	"\aresults\x18\x01 \x03(\v2..muxcore.notification.apprise.v1.ChannelResultR\aresults\"\x83\x01\n" +
	"\rChannelResult\x12B\n" +
	"\achannel\x18\x01 \x01(\x0e2(.muxcore.notification.apprise.v1.ChannelR\achannel\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xf0\x01\n" +
	"\x10ConfigureRequest\x12B\n" +
	"\achannel\x18\x01 \x01(\x0e2(.muxcore.notification.apprise.v1.ChannelR\achannel\x12[\n" +
	"\bsettings\x18\x02 \x03(\v2?.muxcore.notification.apprise.v1.ConfigureRequest.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\x11ConfigureResponse\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\"\x0f\n" +
	"\rStatusRequest\"\\\n" +
	"\x0eStatusResponse\x12J\n" +
	"\bchannels\x18\x01 \x03(\v2..muxcore.notification.apprise.v1.ChannelStatusR\bchannels\"\x8f\x01\n" +
	"\rChannelStatus\x12B\n" +
	"\achannel\x18\x01 \x01(\x0e2(.muxcore.notification.apprise.v1.ChannelR\achannel\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription*t\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCHANNEL_APPRISE\x10\x01\x12\x13\n" +
	"\x0fCHANNEL_DISCORD\x10\x02\x12\x11\n" +
	"\rCHANNEL_SLACK\x10\x03\x12\x13\n" +
	"\x0fCHANNEL_WEBHOOK\x10\x042\xdf\x02\n" +
	"\x13NotificationService\x12i\n" +
	"\x06Notify\x12..muxcore.notification.apprise.v1.NotifyRequest\x1a/.muxcore.notification.apprise.v1.NotifyResponse\x12r\n" +
	"\tConfigure\x121.muxcore.notification.apprise.v1.ConfigureRequest\x1a2.muxcore.notification.apprise.v1.ConfigureResponse\x12i\n" +
	"\x06Status\x12..muxcore.notification.apprise.v1.StatusRequest\x1a/.muxcore.notification.apprise.v1.StatusResponseBGZEgithub.com/Muxcore-Media/notification-apprise/proto/notifyv1;notifyv1b\x06proto3"

var (
	file_proto_notifyv1_notification_proto_rawDescOnce sync.Once
	file_proto_notifyv1_notification_proto_rawDescData []byte
)

func file_proto_notifyv1_notification_proto_rawDescGZIP() []byte {
	file_proto_notifyv1_notification_proto_rawDescOnce.Do(func() {
		file_proto_notifyv1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notifyv1_notification_proto_rawDesc), len(file_proto_notifyv1_notification_proto_rawDesc)))
	})
	return file_proto_notifyv1_notification_proto_rawDescData
}

var file_proto_notifyv1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_notifyv1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_notifyv1_notification_proto_goTypes = []any{
	(Channel)(0),              // 0: muxcore.notification.apprise.v1.Channel
	(*NotifyRequest)(nil),     // 1: muxcore.notification.apprise.v1.NotifyRequest
	(*NotifyResponse)(nil),    // 2: muxcore.notification.apprise.v1.NotifyResponse
	(*ChannelResult)(nil),     // 3: muxcore.notification.apprise.v1.ChannelResult
	(*ConfigureRequest)(nil),  // 4: muxcore.notification.apprise.v1.ConfigureRequest
	(*ConfigureResponse)(nil), // 5: muxcore.notification.apprise.v1.ConfigureResponse
	(*StatusRequest)(nil),     // 6: muxcore.notification.apprise.v1.StatusRequest
	(*StatusResponse)(nil),    // 7: muxcore.notification.apprise.v1.StatusResponse
	(*ChannelStatus)(nil),     // 8: muxcore.notification.apprise.v1.ChannelStatus
	nil,                       // 9: muxcore.notification.apprise.v1.NotifyRequest.FieldsEntry
	nil,                       // 10: muxcore.notification.apprise.v1.ConfigureRequest.SettingsEntry
}
var file_proto_notifyv1_notification_proto_depIdxs = []int32{
	0,  // 0: muxcore.notification.apprise.v1.NotifyRequest.channels:type_name -> muxcore.notification.apprise.v1.Channel
	9,  // 1: muxcore.notification.apprise.v1.NotifyRequest.fields:type_name -> muxcore.notification.apprise.v1.NotifyRequest.FieldsEntry
	3,  // 2: muxcore.notification.apprise.v1.NotifyResponse.results:type_name -> muxcore.notification.apprise.v1.ChannelResult
	0,  // 3: muxcore.notification.apprise.v1.ChannelResult.channel:type_name -> muxcore.notification.apprise.v1.Channel
	0,  // 4: muxcore.notification.apprise.v1.ConfigureRequest.channel:type_name -> muxcore.notification.apprise.v1.Channel
	10, // 5: muxcore.notification.apprise.v1.ConfigureRequest.settings:type_name -> muxcore.notification.apprise.v1.ConfigureRequest.SettingsEntry
	8,  // 6: muxcore.notification.apprise.v1.StatusResponse.channels:type_name -> muxcore.notification.apprise.v1.ChannelStatus
	0,  // 7: muxcore.notification.apprise.v1.ChannelStatus.channel:type_name -> muxcore.notification.apprise.v1.Channel
	1,  // 8: muxcore.notification.apprise.v1.NotificationService.Notify:input_type -> muxcore.notification.apprise.v1.NotifyRequest
	4,  // 9: muxcore.notification.apprise.v1.NotificationService.Configure:input_type -> muxcore.notification.apprise.v1.ConfigureRequest
	6,  // 10: muxcore.notification.apprise.v1.NotificationService.Status:input_type -> muxcore.notification.apprise.v1.StatusRequest
	2,  // 11: muxcore.notification.apprise.v1.NotificationService.Notify:output_type -> muxcore.notification.apprise.v1.NotifyResponse
	5,  // 12: muxcore.notification.apprise.v1.NotificationService.Configure:output_type -> muxcore.notification.apprise.v1.ConfigureResponse
	7,  // 13: muxcore.notification.apprise.v1.NotificationService.Status:output_type -> muxcore.notification.apprise.v1.StatusResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_notifyv1_notification_proto_init() }
func file_proto_notifyv1_notification_proto_init() {
	if File_proto_notifyv1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notifyv1_notification_proto_rawDesc), len(file_proto_notifyv1_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notifyv1_notification_proto_goTypes,
		DependencyIndexes: file_proto_notifyv1_notification_proto_depIdxs,
		EnumInfos:         file_proto_notifyv1_notification_proto_enumTypes,
		MessageInfos:      file_proto_notifyv1_notification_proto_msgTypes,
	}.Build()
	File_proto_notifyv1_notification_proto = out.File
	file_proto_notifyv1_notification_proto_goTypes = nil
	file_proto_notifyv1_notification_proto_depIdxs = nil
}
